apiVersion: apps/v1
kind: Deployment
metadata:
  name: commander-cache
spec:
  template:
    spec:
      containers:
        - image: quay.io/gmagnotta/commander-cache:latest
          name: commander-cache
