---
#
# Playbook to create an installation of an AMQ Broker
#
# It will provision an user with username "user" and password "password"
#
- name: Deploy AMQ Broker in OpenShift cluster
  hosts: localhost
  vars:
    project: "amqbroker-project"
  tasks:

    - name: Create Subscription
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: amq-broker-rhel8
            namespace: "{{ project }}"
          spec:
            channel: 7.11.x
            name: amq-broker-rhel8
            installPlanApproval: Automatic
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: amq-broker-operator.v7.11.4-opr-1

    - name: Wait for Operator Installation
      ansible.builtin.pause:
        minutes: 5
        prompt: "check that operator is installed"

    - name: Create Secret for ActiveMQArtemis
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: custom-jaas-config
            namespace: "{{ project }}"
          data:
            login.config: >-
              YWN0aXZlbXEgewogICBvcmcuYXBhY2hlLmFjdGl2ZW1xLmFydGVtaXMuc3BpLmNvcmUuc2VjdXJpdHkuamFhcy5Qcm9wZXJ0aWVzTG9naW5Nb2R1bGUgc3VmZmljaWVudAogICAgICByZWxvYWQ9dHJ1ZQogICAgICBvcmcuYXBhY2hlLmFjdGl2ZW1xLmphYXMucHJvcGVydGllcy51c2VyPSJuZXctdXNlcnMucHJvcGVydGllcyIKICAgICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5qYWFzLnByb3BlcnRpZXMucm9sZT0ibmV3LXJvbGVzLnByb3BlcnRpZXMiOwoKICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5hcnRlbWlzLnNwaS5jb3JlLnNlY3VyaXR5LmphYXMuUHJvcGVydGllc0xvZ2luTW9kdWxlIHN1ZmZpY2llbnQKICAgICAgcmVsb2FkPWZhbHNlCiAgICAgIG9yZy5hcGFjaGUuYWN0aXZlbXEuamFhcy5wcm9wZXJ0aWVzLnVzZXI9ImFydGVtaXMtdXNlcnMucHJvcGVydGllcyIKICAgICAgb3JnLmFwYWNoZS5hY3RpdmVtcS5qYWFzLnByb3BlcnRpZXMucm9sZT0iYXJ0ZW1pcy1yb2xlcy5wcm9wZXJ0aWVzIgogICAgICBiYXNlRGlyPSIvaG9tZS9qYm9zcy9hbXEtYnJva2VyL2V0YyI7Cn07Cg==
            new-roles.properties: dXNlcj11c2Vy
            new-users.properties: dXNlcj1wYXNzd29yZAo=
          type: Opaque

    - name: Create ActiveMQArtemis
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: broker.amq.io/v1beta1
          kind: ActiveMQArtemis
          metadata:
            name: amqbroker
            namespace: "{{ project }}"
          spec:
            acceptors:
            - name: my-acceptor
              protocols: all
              port: 61616
            deploymentPlan:
              size: 1
              image: placeholder
              requireLogin: false
              persistenceEnabled: true
              journalType: nio
              messageMigration: true
              extraMounts:
                secrets:
                - "custom-jaas-config"
            console:
              expose: true
            brokerProperties:
            - securityRoles.#.user.createAddress=true
            - securityRoles.#.user.deleteAddress=true
            - securityRoles.#.user.createDurableQueue=true
            - securityRoles.#.user.deleteDurableQueue=true
            - securityRoles.#.user.createNonDurableQueue=true
            - securityRoles.#.user.deleteNonDurableQueue=true
            - securityRoles.#.user.send=true
            - securityRoles.#.user.consume=true
            - securityRoles.#.user.browse=true