---
#
# Playbook to deploy OCP Virtualization
#

- name: Deploy OCP Virtualization in OpenShift cluster
  hosts: localhost
  # vars:
  #   project: "openshift-cnv"
  tasks:

    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-cnv

    - name: Create OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: kubevirt-hyperconverged-group
            namespace: openshift-cnv
          spec:
            targetNamespaces:
              - openshift-cnv

    - name: Create Subscription
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: hco-operatorhub
            namespace: openshift-cnv
          spec:
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            name: kubevirt-hyperconverged
            #startingCSV: kubevirt-hyperconverged-operator."{{ version }}"
            channel: "stable"
            installPlanApproval: Automatic
            config:
              env:
              - name: KVM_EMULATION
                value: "true"

    - name: Search pod
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - "name = hyperconverged-cluster-operator"
          - "app.kubernetes.io/component = deployment"
          - "app.kubernetes.io/part-of = hyperconverged-cluster"
          - "app.kubernetes.io/managed-by = olm"
      register: pod_list
      until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
      retries: 10
      delay: 10

    - name: Create HCO
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: hco.kubevirt.io/v1beta1
          kind: HyperConverged
          metadata:
            name: kubevirt-hyperconverged
            namespace: openshift-cnv
          spec:

# HostPathProvisioner (HPP) custom resource, you can create virtual machines that
# use local node storage.

    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-nmstate

    - name: Create OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: openshift-nmstate-kzd99
            namespace: openshift-nmstate
          spec:
            targetNamespaces:
              - openshift-nmstate
            upgradeStrategy: Default

    - name: Create Subscription
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: kubernetes-nmstate-operator
            namespace: openshift-nmstate
          spec:
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            name: kubernetes-nmstate-operator
            #startingCSV: kubernetes-nmstate-operator.4.15.0-202404242206
            channel: "stable"
            installPlanApproval: Automatic
