name = "demo93-microshift"
description = "Giuseppe Demo"
version = "0.0.1"
modules = []
groups = []
distro = "rhel-93"

[[packages]]
name = "podman"

[[packages]]
name = "skopeo"

[[packages]]
name = "openssh-server"

[[packages]]
name = "buildah"

[[packages]]
name = "cosign"

[[packages]]
name = "microshift"

[[packages]]
name = "microshift-greenboot"

[[packages]]
name = "microshift-networking"

[[packages]]
name = "microshift-selinux"

[[containers]]
source = "quay.io/gmagnotta/hello-tomcat:stable"

[customizations.firewall]
ports = ["22:tcp", "80:tcp", "443:tcp", "5353:udp", "6443:tcp", "8080:tcp", "30000-32767:tcp", "30000-32767:udp"]

[customizations.services]
enabled = ["sshd", "microshift"]

[customizations.firewall.services]
enabled = ["mdns", "ssh", "http", "https"]

[[customizations.firewall.zones]]
name = "trusted"
sources = ["10.42.0.0/16", "169.254.169.1"]

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:34aecf85264e97c42b9e39c0a9424a9dea4fea2eb0d515fbcca1d5769fba934b"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a677d4baf4f98ec8d1124a3eb3c40aa5bdb75ac07b6b9c56d1569a52f2c2cb2e"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d13a78f6da1a924beb5178da7e509335a38a918474f1b6f791dcdfd6d93239a4"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e5f868e7542c8811bce53bb1bd928693e16e41d91f3495d233908f96f8e2a77b"

[[containers]]
source = "registry.access.redhat.com/ubi8/openssl@sha256:9e743d947be073808f7f1750a791a3dbd81e694e37161e8c6c6057c2c342d671"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e2cc8dd2e109439d49ff1555b33f980fd0f1a36fd1f19ad449510852511d7c89"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b47df6baa7da64933f574bbfb110ed81efb926e6a730dfd846efcf2001093741"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:891954fe689c0cb146da3f16858ce36d1a9b49a87fe8531cf6cefaf492245371"

[[containers]]
source = "registry.redhat.io/lvms4/topolvm-rhel9@sha256:d0c039eba8157965b0a7971ad4e01576d2c1e31b09fe938554163b324cc4dc73"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:caa0bbab808d8cbed476e8fa3e296ceb90f8d7d253e36588fa77e639ea389d55"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-livenessprobe@sha256:829a8e4d34404abbd22fddb6ebfa0f74daa55f2697fb147da77b83fc8b473d8c"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-resizer@sha256:7ee0257998b7f804fcde9c095b4dc240c510eb316d7223e8485f701b5c9f2fbf"

[[containers]]
source = "registry.redhat.io/openshift4/ose-csi-external-provisioner@sha256:b453a5c76ba4e975a978e31a51531b1d6233723b0d944622caf7844dedf9ad5a"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:778e5a5d482ce97cf8dd3992d66f069822b47aa9e98ddd277cbad6bd3ccbf35b"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:eb66b0a8cb2727f7f6ba75e1fa65c3ed4446ead93ee0dc25b5e83b708e1df68c"

[[containers]]
source = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8c5b849b21ece6ba56253de2ac412394a022c5c8389eb4db4e660b17c2273820"

