---
#
# Playbook to create an installation of kafka
#
# see https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/security/tls-auth/connect.yaml
#
- name: Deploy kafka in OpenShift cluster
  hosts: localhost
  vars:
    project: "kafka"
    cluster_name: "my-cluster"
  tasks:

    - name: Create Subscription
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: amq-streams
            namespace: "{{ project }}"
          spec:
            channel: stable
            name: amq-streams
            installPlanApproval: Automatic
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: amqstreams.v2.6.0-1

    - name: Wait for Operator Installation
      ansible.builtin.pause:
        minutes: 5
        prompt: "check that operator is installed"

    - name: Create Kafka Cluster
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: Kafka
          metadata:
            name: "{{ cluster_name }}"
            namespace: "{{ project }}"
          spec:
            kafka:
              authorization:
                type: simple
              config:
                offsets.topic.replication.factor: 3
                transaction.state.log.replication.factor: 3
                transaction.state.log.min.isr: 2
                default.replication.factor: 3
                min.insync.replicas: 2
                inter.broker.protocol.version: '3.6'
                auto.create.topics.enable: 'true'
              storage:
                type: persistent-claim
                size: 5Gi
              listeners:
                - name: plain
                  port: 9092
                  type: internal
                  tls: false
                  configuration:
                    useServiceDnsDomain: true
                - name: tls
                  port: 9093
                  type: internal
                  tls: true
                  authentication:
                    type: tls
              version: 3.6.0
              replicas: 3
            entityOperator:
              topicOperator: {}
              userOperator: {}
            zookeeper:
              storage:
                type: persistent-claim
                size: 5Gi
              replicas: 3

    # - name: Create Kafka Topic
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: kafka.strimzi.io/v1beta2
    #       kind: KafkaTopic
    #       metadata:
    #         name: topic-name-1
    #         namespace: "{{ project }}"
    #         labels:
    #           strimzi.io/cluster: my-cluster
    #       spec:
    #         topicName: topic-name-1

    - name: Extract the cluster CA certificate
      shell: oc get secret "{{ cluster_name }}"-cluster-ca-cert -n "{{ project }}" -o jsonpath='{.data.ca\.p12}' | base64 -d > /tmp/ca.p12

    - name: Extract the cluster CA password
      shell: oc get secret "{{ cluster_name }}"-cluster-ca-cert -n "{{ project }}" -o jsonpath='{.data.ca\.password}' | base64 -d > /tmp/ca.password