---
#
# Playbook to create a Tekton Pipeline for cross compiling
#

# Create Project
- import_playbook: ../../container-utils/playbooks/playbook_initialize_project.yaml

- name: Perform cross compiling in OpenShift cluster
  hosts: localhost
  vars:
    project: "crosscompile"
    webhook_password: "mywebhookpassword"
    gitrepo: "https://github.com/gmagnotta/pico"
    builderimage: "quay.io/gmagnotta/armv5-crosscompiler"
    runtimeimage: "docker.io/library/debian@sha256:4978e36829464df16ff6e5da9db47c9bde43bcdfd782663fd903d96874b65286"
  tasks:

    - name: Import buildah_s2i_task
      shell: "oc apply -n {{ project }} -f https://raw.githubusercontent.com/gmagnotta/buildah_s2i/main/buildah_s2i_task.yaml"

    - name: Import buildah_s2i_runtime_task
      shell: "oc apply -n {{ project }} -f https://raw.githubusercontent.com/gmagnotta/buildah_s2i/main/buildah_s2i_runtime_task.yaml"

    - name: Import generate_sbom_task
      shell: "oc apply -n {{ project }} -f https://raw.githubusercontent.com/gmagnotta/container-utils/main/tekton/generate_sbom_task.yaml"

    - name: Import vulnerability_sbom_task
      shell: "oc apply -n {{ project }} -f https://raw.githubusercontent.com/gmagnotta/container-utils/main/tekton/vulnerability_sbom_task.yaml"

    - name: Check if secret is linked
      shell: "oc get serviceaccount pipeline -n {{ project }} -o json | jq -r '.secrets[] | select(.name | test(\"redhatregistryio\")).name'"
      register: redhatregistryio

    # - name: Print value
    #   ansible.builtin.debug:
    #     msg: "redhatregistryio={{ redhatregistryio.stdout }}"

    - name: Link secret to pipeline
      command: "oc secrets link pipeline redhatregistryio -n {{ project }}"
      when: redhatregistryio.stdout == ""

    - name: Create Image Stream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: builder-image
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true
            tags:
            - annotations:
                description: Cross compile toolchain
              from:
                kind: DockerImage
                name: "{{ builderimage }}"
              name: latest
              referencePolicy:
                type: Local

    - name: Create Image Stream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: runtime-image
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true
            tags:
            - annotations:
                description: Runtime Image
              from:
                kind: DockerImage
                name: "{{ runtimeimage }}"
              name: latest
              referencePolicy:
                type: Local

    - name: Create ImageStream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: compiled-artifacts
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true

    - name: Create ImageStream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: crosscompiled
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true

    - name: Create Pipeline
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: tekton.dev/v1beta1
          kind: Pipeline
          metadata:
            name: crosscompile
            namespace: "{{ project }}"
          spec:
            workspaces:
              - name: src
              - name: env
              - name: secureenv
              - name: artifacts
            tasks:
              - name: fetch-repository
                taskRef:
                  name: git-clone
                  kind: ClusterTask
                workspaces:
                  - name: output
                    workspace: src
                params:
                  - name: url
                    value: "{{ gitrepo }}"
                  - name: deleteExisting
                    value: "true"
              - name: build
                taskRef:
                  name: buildah-s2i
                runAfter:
                  - fetch-repository
                workspaces:
                  - name: source
                    workspace: src
                  - name: environment
                    workspace: env
                  - name: secureenvironment
                    workspace: secureenv
                  - name: artifacts
                    workspace: artifacts
                params:
                  - name: BUILDER_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/builder-image"
                  - name: TLSVERIFY
                    value: "false"
                  - name: OUTPUT_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/compiled-artifacts"
              - name: create-runtime
                taskRef:
                  name: buildah-s2i-runtime
                runAfter:
                  - build
                workspaces:
                  - name: source
                    workspace: src
                params:
                  - name: RUNTIME_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/runtime-image"
                  - name: TLSVERIFY
                    value: "false"
                  - name: SOURCE_IMAGE
                    value: "$(tasks.build.results.IMAGE_URL)@$(tasks.build.results.IMAGE_DIGEST)"
                  - name: OUTPUT_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/crosscompiled"
                  - name: SRC_ARTIFACT
                    value: "/tmp/src/server"
                  - name: DESTINATION_URL
                    value: "/usr/bin/"
              - name: generate-sbom
                taskRef:
                  name: generate-sbom
                workspaces:
                  - name: source
                    workspace: src
                runAfter:
                  - create-runtime
                params:
                  - name: IMAGETOSCAN
                    value: "$(tasks.create-runtime.results.IMAGE_URL)@$(tasks.create-runtime.results.IMAGE_DIGEST)"
                  - name: SBOMFILE
                    value: "$(workspaces.source.path)/crosscompile-sbom.cdx"
                  - name: TLSVERIFY
                    value: "false"
                  - name: OUTPUT_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/crosscompiled:sbom"
              - name: vuln-scan
                taskRef:
                  name: vulnerability-sbom
                workspaces:
                  - name: source
                    workspace: src
                runAfter:
                  - generate-sbom
                params:
                  - name: SBOM
                    value: "$(workspaces.source.path)/crosscompile-sbom.cdx"

    - name: Create TriggerBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerBinding
          metadata:
            name: event-binding
            namespace: "{{ project }}"
          spec:
            params:
              - name: git-repository-url
                value: $(body.repository.url) # use $(body.repository.clone_url) for gitea see https://docs.gitea.com/usage/webhooks#event-information

    - name: Create TriggerTemplate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: TriggerTemplate
          metadata:
            name: push-trigger-template
            namespace: "{{ project }}"
          spec:
            params:
            - name: git-repository-url
              description: The git repository url
            resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: crosscompile-
              spec:
                pipelineRef:
                  name: crosscompile
                workspaces:
                  - name: src
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
                        storageClassName: ocs-external-storagecluster-ceph-rbd
                        volumeMode: Filesystem
                      status: {}
                  - emptyDir: {}
                    name: env
                  - emptyDir: {}
                    name: secureenv
                  - name: artifacts
                    emptyDir: {}

    - name: Create EventListener
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: EventListener
          metadata:
            name: listener
            namespace: "{{ project }}"
          spec:
            serviceAccountName: pipeline
            triggers:
              - name: trigger
                interceptors:
                  - ref:
                      name: "github"
                      kind: ClusterInterceptor
                      apiVersion: triggers.tekton.dev
                    params:
                    - name: "secretRef"
                      value:
                        secretName: git-secret
                        secretKey: secretToken
                    - name: "eventTypes"
                      value: ["push"]
                bindings:
                  - ref: event-binding    
                template:
                  ref: push-trigger-template

    - name: Create Secret
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: git-secret
            namespace: "{{ project }}"
          data:
            secretToken: "{{ webhook_password | b64encode }}"

    - name: Create Route
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            labels:
              app.kubernetes.io/managed-by: EventListener
              app.kubernetes.io/part-of: Triggers
              eventlistener: listener
            name: el-listener
            namespace: "{{ project }}"
          spec:
            port:
              targetPort: http-listener
            to:
              kind: Service
              name: el-listener
              weight: 100
