---
- name: Generate Self signed TSL Certificate
  hosts: localhost
  vars:
    hostname: "sso-ingress.localdomain"
  tasks:
    - name: Create private key
      community.crypto.openssl_privatekey:
        path: files/certificate.key
        #size: 2048

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: files/certificate.key
        common_name: "{{ hostname }}"
        organization_name: Demo
        subject_alt_name:
          - "DNS:{{ hostname }}"
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        csr_content: "{{ csr.csr }}"
        provider: selfsigned
        selfsigned_not_after: "+3650d"
        path: files/certificate.pem
        privatekey_path: files/certificate.key