---
#
# Playbook to create an installation of Tomcat
#
- name: Deploy Tomcat in OpenShift cluster
  hosts: localhost
  vars:
    project: "hello-tomcat"
  tasks:

    - name: Link secret to pipeline
      command: "oc secrets link pipeline redhatregistryio -n {{ project }}"

    - name: Create Image Stream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: jws56-openjdk11-openshift-rhel8
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true
            tags:
            - annotations:
                description: Red Hat JBoss WS 5.6 Image
              from:
                kind: DockerImage
                name: registry.redhat.io/jboss-webserver-5/jws56-openjdk11-openshift-rhel8
              name: latest
              referencePolicy:
                type: Local
    
    - name: Create ImageStream
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: image.openshift.io/v1
          kind: ImageStream
          metadata:
            name: hello-tomcat
            namespace: "{{ project }}"
          spec:
            lookupPolicy:
              local: true

    - name: Create Pipeline
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: tekton.dev/v1beta1
          kind: Pipeline
          metadata:
            name: hello-tomcat
            namespace: "{{ project }}"
          spec:
            params:
              - name: repo-url
            workspaces:
              - name: src
              - name: env
              - name: secureenv
              - name: artifacts
            tasks:
              - name: fetch-repository
                taskRef:
                  name: git-clone
                  kind: ClusterTask
                workspaces:
                  - name: output
                    workspace: src
                params:
                  - name: url
                    value: $(params.repo-url)
                  - name: deleteExisting
                    value: "true"
              - name: build
                taskRef:
                  name: buildah-s2i
                runAfter:
                  - fetch-repository
                workspaces:
                  - name: source
                    workspace: src
                  - name: environment
                    workspace: env
                  - name: secureenvironment
                    workspace: secureenv
                  - name: artifacts
                    workspace: artifacts
                params:
                  - name: BUILDER_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/jws56-openjdk11-openshift-rhel8"
                  - name: TLSVERIFY
                    value: "false"
                  - name: OUTPUT_IMAGE
                    value: "image-registry.openshift-image-registry.svc:5000/{{ project }}/hello-tomcat"
                  - name: PATH_CONTEXT
                    value: "hello-tomcat"
                  - name: INCREMENTAL
                    value: "true"
              - name: deploy
                taskRef:
                  name: openshift-client
                  kind: ClusterTask
                runAfter:
                  - build
                workspaces:
                  - name: manifest-dir
                    workspace: src
                params:
                  - name: SCRIPT
                    value: |
                      cd $(workspaces.manifest-dir.path)/hello-tomcat/k8s/overlay/dev
                      
                      cat <<EOF > kustomization.yaml
                      apiVersion: kustomize.config.k8s.io/v1beta1
                      kind: Kustomization

                      resources:
                      - ../../base
                      images:
                      - name: hello-tomcat
                        newName: $(tasks.build.results.IMAGE_URL)@$(tasks.build.results.IMAGE_DIGEST)
                      EOF

                      oc apply -k .
