---
project: "myproject"
registry_name: "registryredhatio"
registry_hostname: "registry.redhat.io"
registry_username: "myuser"
registry_password: "mypassword"
create_builder_secret: false
create_operator_group: false