---
#
# Playbook to create Service interconnect in a namespace that provides services
#

- name: Deploy Service Interconnect in a namespace
  hosts: localhost
  vars:
    project: "project"
    # for installing cluster wide use project: openshift-operators
  
  tasks:

    - name: Create Subscription
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: skupper-operator
            namespace: "{{ project }}"
          spec:
            channel: stable-1.8
            installPlanApproval: Automatic
            name: skupper-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            #startingCSV: skupper-operator.v1.8.1-rh-3
        wait: true
        wait_condition: 
          reason: AllCatalogSourcesHealthy
          status: false
          type: CatalogSourcesUnhealthy
        wait_timeout: 300
    
    - name: Search for skupper pod
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ project }}"
        label_selectors:
          - "application = skupper-site-controller"
        wait: yes
        wait_sleep: 10
        wait_timeout: 360

    - name: Perform OC login
      shell: oc login --token=$K8S_AUTH_API_KEY --server=$K8S_AUTH_HOST

    - name: Skupper init
      shell: skupper init -n {{ project }}

    - name: Skupper token create
      shell: skupper token create -n {{ project }} secret.token