---
- name: OCP Login
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: Check ocp credential exists
      ansible.builtin.assert:
        that:
          - ocp_url is defined
          - ocp_url != ""
          - ocp_username is defined
          - ocp_username != ""
          - ocp_password is defined
          - ocp_password != ""
        fail_msg: "ocp credentials not valid, export the correct values"
    
    - name: login to openshift
      ansible.builtin.command: oc login {{ ocp_url }} -u {{ ocp_username }} -p {{ ocp_password }} --insecure-skip-tls-verify=true
      register: ocp_login_result
      changed_when: false

    - name: Check if oc login succeeded
      ansible.builtin.fail:
        msg: "oc login failed!"
      when: ocp_login_result.rc != 0

- name: Create Project
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.project

- name: Provision Postgresql
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.postgresql.provision

- name: Setup Schema Postgresql
  hosts: localhost
  vars_files:
    - variables.yml
  vars:
    postgresql_file: files/schema.sql
  roles:
    - gmagnotta.ocp.postgresql.runsql

- name: Load data into Postgresql
  hosts: localhost
  vars_files:
    - variables.yml
  vars:
    postgresql_file: files/import.sql
  roles:
    - gmagnotta.ocp.postgresql.runsql

- name: Configure postgresql for CDC
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.postgresql.enablepublication

- name: Deploy commander application
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:

    - name: Deploy resources
      kubernetes.core.k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='files/k8s/commander/overlays/prod/') }}"
      register: oc_apply_result

- name: Initialize skupper
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:

    - name: skupper init
      ansible.builtin.command: skupper init -n {{ project }}

    - name: skupper generate token
      ansible.builtin.command: skupper token create -n {{ project }} secret.token

    - name: skupper expose postgresql
      ansible.builtin.command: skupper expose deployment/postgresql --port 5432 -n {{ project }}