---
- name: Setup kubeconfig
  hosts: localhost
  tasks:

    - name: Create ~/.kube
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0700'

    - name: copy config
      ansible.builtin.copy:
        src: kubeconfig
        dest: ~/.kube/config
        mode: '0644'

- name: Create Project
  hosts: localhost
  vars_files:
    - variables_edge.yml
  roles:
    - gmagnotta.ocp.project

- name: Deploy commander cache application
  hosts: localhost
  vars_files:
    - variables_edge.yml
  tasks:

    - name: Deploy resources
      kubernetes.core.k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='files/k8s/commander-cache/overlays/prod/') }}"
      register: oc_apply_result

- name: Provision Debezium Server
  hosts: localhost
  vars_files:
    - variables_edge.yml
  roles:
    - gmagnotta.ocp.debeziumserver

- name: Initialize skupper in edge site
  hosts: localhost
  vars_files:
    - variables_edge.yml
  tasks:

    - name: Wait for user confirmation
      ansible.builtin.pause:
        prompt: "Press ENTER to continue"

    - name: skupper init in namespace {{ project }}
      ansible.builtin.command: skupper init -n {{ project }}

    - name: skupper link create in namespace {{ project }}
      ansible.builtin.command: skupper link create --name core -n {{ project }} secret.token