---
- name: OCP Login
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.login

- name: Regenerate Skupper token
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:

    - name: skupper generate token
      ansible.builtin.command: skupper token create --expiry 1h -n {{ project }} secret.token