---
- name: OCP Login
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:
    - name: Check ocp credential exists
      ansible.builtin.assert:
        that:
          - ocp_url is defined
          - ocp_url != ""
          - ocp_username is defined
          - ocp_username != ""
          - ocp_password is defined
          - ocp_password != ""
        fail_msg: "ocp credentials not valid, export the correct values"
    
    - name: login to openshift
      ansible.builtin.command: oc login {{ ocp_url }} -u {{ ocp_username }} -p {{ ocp_password }} --insecure-skip-tls-verify=true
      register: ocp_login_result
      changed_when: false

    - name: Check if oc login succeeded
      ansible.builtin.fail:
        msg: "oc login failed!"
      when: ocp_login_result.rc != 0

- name: Create Project
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.project

- name: Deploy commander cache application
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:

    - name: Deploy resources
      kubernetes.core.k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='files/k8s/commander-cache/overlays/prod/') }}"
      register: oc_apply_result

- name: Provision Debezium Server
  hosts: localhost
  vars_files:
    - variables.yml
    - variables_remote.yml
  roles:
    - gmagnotta.ocp.debeziumserver

- name: Initialize skupper
  hosts: localhost
  vars_files:
    - variables.yml
    - variables_remote.yml
  tasks:

    - name: skupper init in namespace {{ project }}
      ansible.builtin.command: skupper init -n {{ project }}

    - name: skupper link create in namespace {{ project }}
      ansible.builtin.command: skupper link create -n {{ project }} secret.token