---
- name: Setup kubeconfig
  hosts: localhost
  tasks:

    - name: Create ~/.kube
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0700'

    - name: copy config
      ansible.builtin.copy:
        src: kubeconfig
        dest: ~/.kube/config
        mode: '0644'

- name: Create skupper link in edge site
  hosts: localhost
  vars_files:
    - variables_edge.yml
  tasks:

    - name: skupper link create in namespace {{ project }}
      ansible.builtin.command: skupper link create --name core -n {{ project }} secret.token