---
- name: OCP Login
  hosts: localhost
  vars_files:
    - variables_remote.yml
  roles:
    - gmagnotta.ocp.login

- name: Create Project
  hosts: localhost
  vars_files:
    - variables_remote.yml
  roles:
    - gmagnotta.ocp.project

- name: Deploy commander cache application
  hosts: localhost
  vars_files:
    - variables_remote.yml
  tasks:

    - name: Deploy resources
      kubernetes.core.k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='files/k8s/commander-cache/overlays/prod/') }}"
      register: oc_apply_result

- name: Provision Debezium Server
  hosts: localhost
  vars_files:
    - variables_remote.yml
  roles:
    - gmagnotta.ocp.debeziumserver

- name: Initialize skupper
  hosts: localhost
  vars_files:
    - variables_remote.yml
  tasks:

    - name: Wait for user confirmation
      ansible.builtin.pause:
        prompt: "Press ENTER to continue"

    - name: skupper init in namespace {{ project }}
      ansible.builtin.command: skupper init -n {{ project }}

    - name: skupper link create in namespace {{ project }}
      ansible.builtin.command: skupper link create -n {{ project }} secret.token