---
#
# Playbook to deploy Developer HUB
#
- name: Deploy Developer HUB Secrets
  hosts: localhost
  vars:
    sso_client_id: "RHDH"
    sso_client_secret: "Changeme"
    github_token: "Changeme"
    github_client_id: "Changeme"
    github_client_secret: "Changeme"
    argocd_token: "Changeme"

  tasks:

    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: developerhub

    - name: Create Service Account
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: rhdh-sa-token
            namespace: developerhub
            annotations:
              kubernetes.io/service-account.name: default
          type: kubernetes.io/service-account-token

#
# export OPENSHIFT_TOKEN=$(oc get secret rhdh-sa-token -o go-template='{{.data.token | base64decode}}')
#

    - name: Extract openshift token
      command: "oc get secret rhdh-sa-token -n developerhub -o go-template --template='{{ '{{' }} .data.token | base64decode {{ '}}' }}'"
      register: openshift_token

    - name: Create ClusterRoleBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: default-view-rhdh
          subjects:
          - kind: ServiceAccount
            name: default
            namespace: developerhub
          roleRef:
            kind: ClusterRole
            name: view
            apiGroup: rbac.authorization.k8s.io

    - name: Create Secret
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          type: Opaque
          metadata:
            name: secrets-rhdh
            namespace: developerhub
          data:
            SSO_CLIENT_ID: "{{ sso_client_id | b64encode }}"
            SSO_CLIENT_SECRET: "{{ sso_client_secret | b64encode }}"
            GITHUB_CLIENT_ID: "{{ github_client_id | b64encode }}"
            GITHUB_CLIENT_SECRET: "{{ github_client_secret | b64encode }}"
            GITHUB_TOKEN: "{{ github_token | b64encode }}"
            OPENSHIFT_TOKEN: "{{ openshift_token.stdout | b64encode }}"
            ARGOCD_AUTH_TOKEN: "{{ argocd_token | b64encode }}"
