name = "rhel8-tomcat"
description = "Giuseppe Demo including a tomcat hello world image"
version = "0.0.1"
modules = []
groups = []
distro = "rhel-89"

[[containers]]
source = "quay.io/gmagnotta/hello-tomcat:stable"

[customizations.firewall]
ports = ["22:tcp", "8080:tcp"]

[[customizations.files]]
path = "/etc/systemd/system/tomcat.service"
mode = "0644"
user = "root"
group = "root"
data = """[Unit]
Description=Podman container-e26f33586180f2804042616c856510aea05e23b0b14cfd9ba03bca44846347c5.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers
[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id --cgroups=no-conmon --rm --sdnotify=conmon -d -ti -p 8080:8080 quay.io/gmagnotta/hello-tomcat:stable
ExecStop=/usr/bin/podman stop --ignore -t 10 --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore -t 10 --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all
[Install]
WantedBy=default.target"""

[customizations.services]
enabled = ["sshd", "tomcat"]

